<?php
	function save_data_to_db($db, $data) {
	 	if(!$db) { die("Connection failed: " . mysqli_connect_error()); }
		
		$query = "INSERT INTO programs (
			program_id,
			program_name,
			provider_name,
			cip_name,
			provider_address,
			provider_website,
			provider_contact_info,
			provider_licensing_agency,
			provider_non_govt_accrediting_org,
			attributes_in_demand,
			attributes_green,
			description_short,
			description_unique_features,
			credentials_degree,
			credentials_credential,
			credentials_license,
			features_wia_eligible,
			features_child_care_offered_on_site,
			features_assistance_in_obtaining_child_care,
			features_wheelchair_accessible,
			features_career_counseling_available,
			features_customized_training_services_provider,
			features_distance_learning_services_provider,
			features_spanish_spoken_by_staff,
			features_other_languages_spoken_by_staff,
			cost_total,
			cost_tuition,
			cost_books_and_materials,
			cost_supplies_and_tools,
			cost_other,
			info_admission_pre_requisites,
			info_clock_hours,
			info_credit_hours,
			info_calendar_length,
			info_licensing_agency,
			info_provider_type,
			contact_name,
			contact_phone_number,
			contact_phone_number_ext,
			contact_email,
			rating_value,
			rating_count,
			outcomes_data_6_months_this_program_employment_rate_value,
			outcomes_data_6_months_this_program_employment_rate_num,
			outcomes_data_6_months_this_program_wage_quarterly_value,
			outcomes_data_6_months_this_program_wage_quarterly_num,
			outcomes_data_6_months_this_program_wage_yearly_value,
			outcomes_data_6_months_this_program_wage_yearly_num,
			outcomes_data_6_months_this_provider_employment_rate_value,
			outcomes_data_6_months_this_provider_employment_rate_num,
			outcomes_data_6_months_this_provider_wage_quarterly_value,
			outcomes_data_6_months_this_provider_wage_quarterly_num,
			outcomes_data_6_months_this_provider_wage_yearly_value,
			outcomes_data_6_months_this_provider_wage_yearly_num,
			outcomes_data_6_months_related_programs_employment_rate_value,
			outcomes_data_6_months_related_programs_employment_rate_num,
			outcomes_data_6_months_related_programs_wage_quarterly_value,
			outcomes_data_6_months_related_programs_wage_quarterly_num,
			outcomes_data_6_months_related_programs_wage_yearly_value,
			outcomes_data_6_months_related_programs_wage_yearly_num,
			outcomes_data_1_year_this_program_employment_rate_value,
			outcomes_data_1_year_this_program_employment_rate_num,
			outcomes_data_1_year_this_program_retention_rate_value,
			outcomes_data_1_year_this_program_retention_rate_num,
			outcomes_data_1_year_this_program_wage_quarterly_value,
			outcomes_data_1_year_this_program_wage_quarterly_num,
			outcomes_data_1_year_this_program_wage_yearly_value,
			outcomes_data_1_year_this_program_wage_yearly_num,
			outcomes_data_1_year_this_provider_employment_rate_value,
			outcomes_data_1_year_this_provider_employment_rate_num,
			outcomes_data_1_year_this_provider_retention_rate_value,
			outcomes_data_1_year_this_provider_retention_rate_num,
			outcomes_data_1_year_this_provider_wage_quarterly_value,
			outcomes_data_1_year_this_provider_wage_quarterly_num,
			outcomes_data_1_year_this_provider_wage_yearly_value,
			outcomes_data_1_year_this_provider_wage_yearly_num,
			outcomes_data_1_year_related_programs_employment_rate_value,
			outcomes_data_1_year_related_programs_employment_rate_num,
			outcomes_data_1_year_related_programs_retention_rate_value,
			outcomes_data_1_year_related_programs_retention_rate_num,
			outcomes_data_1_year_related_programs_wage_quarterly_value,
			outcomes_data_1_year_related_programs_wage_quarterly_num,
			outcomes_data_1_year_related_programs_wage_yearly_value,
			outcomes_data_1_year_related_programs_wage_yearly_num,
			outcomes_data_2_years_this_program_employment_rate_value,
			outcomes_data_2_years_this_program_employment_rate_num,
			outcomes_data_2_years_this_program_retention_rate_value,
			outcomes_data_2_years_this_program_retention_rate_num,
			outcomes_data_2_years_this_program_wage_quarterly_value,
			outcomes_data_2_years_this_program_wage_quarterly_num,
			outcomes_data_2_years_this_program_wage_yearly_value,
			outcomes_data_2_years_this_program_wage_yearly_num,
			outcomes_data_2_years_this_provider_employment_rate_value,
			outcomes_data_2_years_this_provider_employment_rate_num,
			outcomes_data_2_years_this_provider_retention_rate_value,
			outcomes_data_2_years_this_provider_retention_rate_num,
			outcomes_data_2_years_this_provider_wage_quarterly_value,
			outcomes_data_2_years_this_provider_wage_quarterly_num,
			outcomes_data_2_years_this_provider_wage_yearly_value,
			outcomes_data_2_years_this_provider_wage_yearly_num,
			outcomes_data_2_years_related_programs_employment_rate_value,
			outcomes_data_2_years_related_programs_employment_rate_num,
			outcomes_data_2_years_related_programs_retention_rate_value,
			outcomes_data_2_years_related_programs_retention_rate_num,
			outcomes_data_2_years_related_programs_wage_quarterly_value,
			outcomes_data_2_years_related_programs_wage_quarterly_num,
			outcomes_data_2_years_related_programs_wage_yearly_value,
			outcomes_data_2_years_related_programs_wage_yearly_num
		) VALUES (
			'".$data["program_id"]."',
			'".mysqli_real_escape_string($db, $data["program_name"])."',
			'".mysqli_real_escape_string($db, $data["provider_name"])."',
			'".mysqli_real_escape_string($db, $data["cip_name"])."',
			'".mysqli_real_escape_string($db, $data["provider"]["address"])."',
			'".mysqli_real_escape_string($db, $data["provider"]["website"])."',
			'".mysqli_real_escape_string($db, $data["provider"]["contact_info"])."',
			'".mysqli_real_escape_string($db, $data["provider"]["licensing_agency"])."',
			'".mysqli_real_escape_string($db, $data["provider"]["non_govt_accrediting_org"])."',
			'".mysqli_real_escape_string($db, $data["attributes"]["in_demand"])."',
			'".mysqli_real_escape_string($db, $data["attributes"]["green"])."',
			'".mysqli_real_escape_string($db, $data["description"]["short"])."',
			'".mysqli_real_escape_string($db, $data["description"]["unique_features"])."',
			'".mysqli_real_escape_string($db, $data["credentials"]["degree"])."',
			'".mysqli_real_escape_string($db, $data["credentials"]["credential"])."',
			'".mysqli_real_escape_string($db, $data["credentials"]["license"])."',
			'".mysqli_real_escape_string($db, $data["features"]["wia_eligible"])."',
			'".mysqli_real_escape_string($db, $data["features"]["child_care_offered_on_site"])."',
			'".mysqli_real_escape_string($db, $data["features"]["assistance_in_obtaining_child_care"])."',
			'".mysqli_real_escape_string($db, $data["features"]["wheelchair_accessible"])."',
			'".mysqli_real_escape_string($db, $data["features"]["career_counseling_available"])."',
			'".mysqli_real_escape_string($db, $data["features"]["customized_training_services_provider"])."',
			'".mysqli_real_escape_string($db, $data["features"]["distance_learning_services_provider"])."',
			'".mysqli_real_escape_string($db, $data["features"]["spanish_spoken_by_staff"])."',
			'".mysqli_real_escape_string($db, $data["features"]["other_languages_spoken_by_staff"])."',
			'".mysqli_real_escape_string($db, $data["cost"]["total"])."',
			'".mysqli_real_escape_string($db, $data["cost"]["tuition"])."',
			'".mysqli_real_escape_string($db, $data["cost"]["books_and_materials"])."',
			'".mysqli_real_escape_string($db, $data["cost"]["supplies_and_tools"])."',
			'".mysqli_real_escape_string($db, $data["cost"]["other"])."',
			'".mysqli_real_escape_string($db, $data["info"]["admission_pre_requisites"])."',
			'".mysqli_real_escape_string($db, $data["info"]["clock_hours"])."',
			'".mysqli_real_escape_string($db, $data["info"]["credit_hours"])."',
			'".mysqli_real_escape_string($db, $data["info"]["calendar_length"])."',
			'".mysqli_real_escape_string($db, $data["info"]["licensing_agency"])."',
			'".mysqli_real_escape_string($db, $data["info"]["provider_type"])."',
			'".mysqli_real_escape_string($db, $data["contact"]["name"])."',
			'".mysqli_real_escape_string($db, $data["contact"]["phone_number"])."',
			'".mysqli_real_escape_string($db, $data["contact"]["phone_number_ext"])."',
			'".mysqli_real_escape_string($db, $data["contact"]["email"])."',
			'".mysqli_real_escape_string($db, $data["rating"]["value"])."',
			'".mysqli_real_escape_string($db, $data["rating"]["count"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["6_months"]["this_program"]["employment_rate"]["value"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["6_months"]["this_program"]["employment_rate"]["num_students"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["6_months"]["this_program"]["wage"]["quarterly"]["value"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["6_months"]["this_program"]["wage"]["quarterly"]["num_students"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["6_months"]["this_program"]["wage"]["yearly"]["value"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["6_months"]["this_program"]["wage"]["yearly"]["num_students"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["6_months"]["this_provider"]["employment_rate"]["value"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["6_months"]["this_provider"]["employment_rate"]["num_students"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["6_months"]["this_provider"]["wage"]["quarterly"]["value"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["6_months"]["this_provider"]["wage"]["quarterly"]["num_students"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["6_months"]["this_provider"]["wage"]["yearly"]["value"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["6_months"]["this_provider"]["wage"]["yearly"]["num_students"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["6_months"]["related_programs"]["employment_rate"]["value"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["6_months"]["related_programs"]["employment_rate"]["num_students"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["6_months"]["related_programs"]["wage"]["quarterly"]["value"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["6_months"]["related_programs"]["wage"]["quarterly"]["num_students"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["6_months"]["related_programs"]["wage"]["yearly"]["value"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["6_months"]["related_programs"]["wage"]["yearly"]["num_students"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["1_year"]["this_program"]["employment_rate"]["value"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["1_year"]["this_program"]["employment_rate"]["num_students"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["1_year"]["this_program"]["retention_rate"]["value"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["1_year"]["this_program"]["retention_rate"]["num_students"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["1_year"]["this_program"]["wage"]["quarterly"]["value"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["1_year"]["this_program"]["wage"]["quarterly"]["num_students"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["1_year"]["this_program"]["wage"]["yearly"]["value"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["1_year"]["this_program"]["wage"]["yearly"]["num_students"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["1_year"]["this_provider"]["employment_rate"]["value"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["1_year"]["this_provider"]["employment_rate"]["num_students"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["1_year"]["this_provider"]["retention_rate"]["value"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["1_year"]["this_provider"]["retention_rate"]["num_students"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["1_year"]["this_provider"]["wage"]["quarterly"]["value"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["1_year"]["this_provider"]["wage"]["quarterly"]["num_students"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["1_year"]["this_provider"]["wage"]["yearly"]["value"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["1_year"]["this_provider"]["wage"]["yearly"]["num_students"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["1_year"]["related_programs"]["employment_rate"]["value"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["1_year"]["related_programs"]["employment_rate"]["num_students"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["1_year"]["related_programs"]["retention_rate"]["value"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["1_year"]["related_programs"]["retention_rate"]["num_students"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["1_year"]["related_programs"]["wage"]["quarterly"]["value"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["1_year"]["related_programs"]["wage"]["quarterly"]["num_students"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["1_year"]["related_programs"]["wage"]["yearly"]["value"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["1_year"]["related_programs"]["wage"]["yearly"]["num_students"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["2_years"]["this_program"]["employment_rate"]["value"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["2_years"]["this_program"]["employment_rate"]["num_students"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["2_years"]["this_program"]["retention_rate"]["value"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["2_years"]["this_program"]["retention_rate"]["num_students"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["2_years"]["this_program"]["wage"]["quarterly"]["value"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["2_years"]["this_program"]["wage"]["quarterly"]["num_students"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["2_years"]["this_program"]["wage"]["yearly"]["value"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["2_years"]["this_program"]["wage"]["yearly"]["num_students"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["2_years"]["this_provider"]["employment_rate"]["value"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["2_years"]["this_provider"]["employment_rate"]["num_students"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["2_years"]["this_provider"]["retention_rate"]["value"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["2_years"]["this_provider"]["retention_rate"]["num_students"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["2_years"]["this_provider"]["wage"]["quarterly"]["value"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["2_years"]["this_provider"]["wage"]["quarterly"]["num_students"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["2_years"]["this_provider"]["wage"]["yearly"]["value"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["2_years"]["this_provider"]["wage"]["yearly"]["num_students"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["2_years"]["related_programs"]["employment_rate"]["value"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["2_years"]["related_programs"]["employment_rate"]["num_students"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["2_years"]["related_programs"]["retention_rate"]["value"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["2_years"]["related_programs"]["retention_rate"]["num_students"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["2_years"]["related_programs"]["wage"]["quarterly"]["value"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["2_years"]["related_programs"]["wage"]["quarterly"]["num_students"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["2_years"]["related_programs"]["wage"]["yearly"]["value"])."',
			'".mysqli_real_escape_string($db, $data["outcomes_data"]["2_years"]["related_programs"]["wage"]["yearly"]["num_students"])."'
		)";

		if(mysqli_query($db, $query)) {
			echo $data["program_id"]." added to database";
		} else {
			echo "Error: ".$query."<br>" . mysqli_error($db);
		}
	}
?>